### ISSUE TITLE
Can't locate object method "new" via package "IO::Handle" when using Zimbra::Expect

### ISSUE THREAD

**Issue by gbkersey** [oetiker/zimbra-expect#2]
I simply added IO::Handle the list use list....

```
--- Expect.pm~	2017-08-07 16:53:41.898785447 -0500
+++ Expect.pm	2017-08-07 16:59:24.778361394 -0500
@@ -3,6 +3,7 @@
 use warnings;
 use IPC::Open2;
 use IO::Select;
+use IO::Handle;
 
 our $VERSION = '0.1.0';
```
BTW, thanks for this...  I was getting tired of using ldap to get info out of Zimbra...  And thanks for rrdtool, mrtg and smokeping!

Cheers!

**Comment by oetiker** [comment]
oh ... would you like to turn this into a PR ?

**Comment by gbkersey** [comment]
sure.  Sorry, I just saw your reply...

**Comment by gbkersey** [comment]
PR created
